openapi: 3.0.3
info:
  title: Vue3 Swagger Verification API
  description: Simple API for Swagger verification
  version: 1.0.0
servers:
  - url: /api
    description: Development server
paths:
  /test:
    get:
      summary: Test endpoint
      description: Returns greeting message with current timestamp
      operationId: getTestMessage
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "hello world yyyymmdd-hhmmss format message"
                    example: "hello world 20231226-143022"
                required:
                  - message
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /sample:
    get:
      summary: Sample endpoint
      description: Returns random value and message
      operationId: getSampleData
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SampleResponse'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    TestResponse:
      type: object
      properties:
        message:
          type: string
          description: Greeting message with timestamp
      required:
        - message
    SampleResponse:
      type: object
      properties:
        value:
          type: integer
          minimum: 1
          maximum: 100
          description: Random number between 1 and 100
        message:
          type: string
          minLength: 5
          maxLength: 5
          pattern: '^[a-zA-Z0-9]{5}$'
          description: 5-character random alphanumeric string
      required:
        - value
        - message
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message
      required:
        - error
